export enum ActivityLogType {
  LOG_IN = 1,
  LOG_OUT = 2,
  LOG_IN_FAILED_ACCOUNT_NOT_FOUND = 3,
  LOG_IN_FAILED_PASSWORD_INCORRECT = 4,
  LOG_IN_FAILED_ACCOUNT_HAS_NO_ROLE = 5,
  LOG_OUT_FAILED_ACCOUNT_NOT_FOUND = 7,
  VISITED_PAGE = 8
}
